"""Perception layer: find WeChat's window, capture it, OCR it, extract the conversation.

Validated facts this module is built on (probed 2026-09-21 on WeChat 4.1 Mac):
  * `screencapture -l <windowid>` returns real content even when WeChat is not frontmost,
    so our HUD floating above it never pollutes the capture.
  * Vision OCR reads Simplified Chinese chat text at conf 1.00 on message bodies;
    errors are rare and confined to unusual glyphs.
  * The window layout is stable: chat list occupies x < ~0.30, chat pane x > ~0.32,
    title bar above y ~0.90, input box below y ~0.09.
"""

from __future__ import annotations

import re
import subprocess
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path

import Quartz

# --- layout constants (normalized 0..1 within the window; tuned on the probe data) ---
CHAT_PANE_X_MIN = 0.32
TITLE_BAR_Y_MAX = 0.90
INPUT_AREA_Y_MIN = 0.24
SIDEBAR_X_MAX = 0.30

# --- content filters ---
TIMESTAMP_RE = re.compile(
    r"^(?:(?:今天|昨天|前天)\s*)?"
    r"(?:\d{1,2}\s*月\s*\d{1,2}\s*日\s*)?"
    r"\d{1,2}\s*[:：]\s*\d{2}(?:\s*[:：]\s*\d{2})?\s*[.。·]?$"
)
UI_NOISE = (r"折叠聊天", r"共\s*\d+", r"搜索", r"发送", r"拖入文件", r"按住说话",
            r"语音输入文字", r"按住鼠标", r"按住 说话", r"输入文字",
            r"^[\w\-\u4e00-\u9fa5]{2,20}[:：].*\.\.\..*[）)]>$")  # folded-chat banner
# Centered, bubble-less rows which WeChat inserts into the conversation.  Geometry
# alone cannot distinguish a wide incoming bubble from one of these rows, while these
# phrases are generated by WeChat rather than typed by a participant.  Keep the rules
# deliberately specific: an ordinary message merely mentioning a group must not stop
# being a reply target.
PUBLIC_INFO_RE = re.compile(
    r"(?:"
    r".+通过扫描.+分享的二维码加入了?群聊"
    r"|.+邀请.+加入了?群聊"
    r"|.+与群里其他人都不是朋友关系[,，]?请注意隐私安全"
    r"|.+(?:退出了群聊|被移出了?群聊)"
    r"|.+修改群名为.+"
    r"|.+(?:发布|修改)了?群公告.+"
    r"|.+已成为新群主"
    r"|.+撤回了一条消息"
    r")"
)
MIN_CONF = 0.30
SHORT_RETRY_MIN_CONF = 0.50  # a guessed glyph is worse than an honest placeholder
USERNAME_H_MAX = 0.026   # sender-name lines render smaller than bubble text
MESSAGE_H_MIN = 0.028
MIN_TEXT_LEN = 1

# `CGWindowListCreateImage` can wait forever inside macOS ScreenCaptureKit. Use
# a separate process for the production path so the timeout can actually kill
# the blocked native call instead of leaving a stuck thread in the HUD process.
SUBPROCESS_CAPTURE_TIMEOUT_S = 3.0


@dataclass
class TextBlock:
    text: str
    conf: float
    x: float
    y: float
    w: float
    h: float

    @property
    def x_right(self) -> float:
        return self.x + self.w

    @property
    def x_center(self) -> float:
        return self.x + self.w / 2


@dataclass
class Message:
    text: str
    side: str          # "them" | "me" | "public" | "unknown"
    y: float           # normalized, top-origin for readability
    conf: float
    h: float = 0.0
    sender: str | None = None
    lines: list[str] = field(default_factory=list)
    # normalized bounding box, kept spanning every folded line — the YOLO overlay draws
    # one box per message, so a 3-line message must cover all 3 lines, not its first
    x: float = 0.0
    w: float = 0.0
    last_y: float = 0.0     # top of the most recent folded line; fold bookkeeping only
    visual_only: bool = False  # a bubble exists, but Vision returned no readable text
    suspected_sender: bool = False  # small isolated OCR row; pixels decide in production
    quote_sender: str | None = None
    quote_text: str | None = None
    analysis_text: str | None = None  # consecutive messages sent to the models
    analysis_body: str | None = None  # exclude quoted history from intent judgment
    analysis_parts: tuple[int, ...] = ()


QUOTE_LINE_RE = re.compile(r"^\s*[|｜]?\s*([^:：\n]{1,24})[:：]\s*(\S.*)$")


def reply_span(messages: list[Message], newest: Message, limit: int = 3) -> list[Message]:
    """Adjacent, visibly separate bubbles from one sender form one reply target."""
    try:
        index = next(i for i, m in enumerate(messages) if m is newest)
    except StopIteration:
        return [newest]
    span = [newest]
    while index > 0 and len(span) < limit:
        previous = messages[index - 1]
        current = span[0]
        gap = current.y - (previous.y + previous.h)
        if (previous.side != "them" or previous.visual_only
                or previous.sender != current.sender or not 0 <= gap <= .07):
            break
        span.insert(0, previous)
        index -= 1
    return span


def reply_text(messages: list[Message]) -> str:
    """Keep a quoted preview attributed, separate from each bubble's own words."""
    parts = []
    for message in messages:
        parts.append(message.text)
        quoted = getattr(message, "quote_text", None)
        if quoted:
            who = getattr(message, "quote_sender", None) or "对方"
            parts.append(f"[引用 {who}: {quoted}]")
    return "\n".join(parts)


@dataclass
class WindowInfo:
    wid: int
    pid: int
    title: str
    x: float
    y: float
    w: float
    h: float


# --------------------------------------------------------------------------- window

# The names WeChat reports for itself and for its main chat window on macOS. Mainland
# builds report 微信; some locales and 4.x builds report WeChat or Weixin. One list,
# matched EXACTLY, because both directions of the substring test that used to live at
# the call sites were wrong: `"WeChat" in owner or "微信" in owner` missed the Weixin
# alias entirely (a 4.x build reporting that name found no window at all, and the panel
# simply disappeared), while accepting any owner that merely *contains* 微信 — 微信读书,
# 微信输入法 and 企业微信 own titled windows that clear the 600x400 gate below, so their
# pixels could be captured and OCR'd as chat text (#50). A new alias is now one edit
# here instead of one edit per call site.
WECHAT_APP_NAMES = ("微信", "WeChat", "Weixin")


def screen_capture_ok() -> bool:
    """False when macOS has not granted Screen Recording to this app.

    Worth checking explicitly: without the grant macOS silently hides every window's
    title, so find_wechat_window() would just report "not found" and the user would see
    the panel disappear for no stated reason.
    """
    try:
        return bool(Quartz.CGPreflightScreenCaptureAccess())
    except Exception:
        return True  # pre-10.15 has no such gate


def request_screen_capture() -> bool:
    """Ask the system to show the Screen Recording prompt (once per app identity)."""
    try:
        return bool(Quartz.CGRequestScreenCaptureAccess())
    except Exception:
        return False


def frontmost_app_is_wechat() -> bool | None:
    """Whether the app currently receiving user input is WeChat.

    The window-ID capture path can read an obscured WeChat window, which is useful for
    OCR but not a safe display boundary: a global floating HUD left above Chrome looks
    as if browser text were analysed. Keep foreground ownership separate from window
    discovery so returning to WeChat can force a fresh capture instead of reusing cache.
    """
    try:
        import AppKit
        app = AppKit.NSWorkspace.sharedWorkspace().frontmostApplication()
        if app is None:
            return None
        bundle = app.bundleIdentifier() or ""
        name = app.localizedName() or ""
        return bundle == "com.tencent.xinWeChat" or name in WECHAT_APP_NAMES
    except Exception:
        return None


def _ax_focused_frame(pid: int) -> tuple[float, float, float, float] | None:
    """(x, y, w, h) of the app's AX-focused window, or None when it cannot be read.

    The focused window is the conversation the user is actually reading — the one
    thing neither the main-window priority nor the area sort can see once chats are
    torn off into detached windows (#91). Same shape as ``fill._ax_rect``: AX and CG
    agree on top-left point coordinates, so the frames compare directly. AX reads
    fail routinely (permission, timing, odd surfaces), so every failure degrades to
    None and the caller falls back to the window-list heuristic unchanged.
    """
    try:
        import ApplicationServices as A

        root = A.AXUIElementCreateApplication(int(pid))
        err, focused = A.AXUIElementCopyAttributeValue(
            root, A.kAXFocusedWindowAttribute, None)
        if err != 0 or focused is None:
            return None

        def attr(element, name):
            err, value = A.AXUIElementCopyAttributeValue(element, name, None)
            return value if err == 0 else None

        raw_pos = attr(focused, A.kAXPositionAttribute)
        raw_size = attr(focused, A.kAXSizeAttribute)
        if raw_pos is None or raw_size is None:
            return None
        ok_pos, point = A.AXValueGetValue(raw_pos, A.kAXValueCGPointType, None)
        ok_size, size = A.AXValueGetValue(raw_size, A.kAXValueCGSizeType, None)
        if not (ok_pos and ok_size):
            return None
        return (float(point.x), float(point.y), float(size.width), float(size.height))
    except Exception:
        return None


def find_wechat_window(previous_wid: int | None = None) -> WindowInfo | None:
    """Read the window the user is chatting in.

    Window ownership is matched exactly against WECHAT_APP_NAMES. It used to be a
    substring test, which missed the ``Weixin`` alias — a 4.x build reporting that name
    found no window at all, so the panel just disappeared — and at the same time let
    any owner containing 微信 through, including sibling apps whose own titled windows
    clear the size gate below (#50).

    This filters on the owning *app*, not on the window, so WeChat's detached
    mini-program and web windows still carry owner ``WeChat`` and stay eligible — that
    is what keeps the main-window-absent fallback working.

    WeChat 4.x users chat in detached windows (the default is 550pt wide, below the
    old 600pt gate — #91), so the largest window is not necessarily the one on
    screen. The app's AX-focused window is: when its frame matches an eligible
    candidate (±2pt), that window wins outright. Only an unreadable or non-chat
    focus falls through to the #50 heuristic — main-window priority, then area,
    then the previous-wid stickiness that keeps equally-sized windows from
    re-picking each tick.
    """
    opts = Quartz.kCGWindowListOptionAll | Quartz.kCGWindowListExcludeDesktopElements
    wins = Quartz.CGWindowListCopyWindowInfo(opts, Quartz.kCGNullWindowID)
    best: WindowInfo | None = None
    eligibles: list[WindowInfo] = []
    for w in wins:
        owner = w.get("kCGWindowOwnerName") or ""
        if owner not in WECHAT_APP_NAMES:
            continue
        title = w.get("kCGWindowName") or ""
        b = dict(w.get("kCGWindowBounds") or {})
        wi = WindowInfo(
            wid=int(w.get("kCGWindowNumber") or 0),
            pid=int(w.get("kCGWindowOwnerPID") or 0),
            title=title,
            x=float(b.get("X", 0)), y=float(b.get("Y", 0)),
            w=float(b.get("Width", 0)), h=float(b.get("Height", 0)),
        )
        # a chat window: titled and roughly window-shaped. 500pt admits WeChat 4.x's
        # default detached chat window; the noise surfaces sampled live (tooltips,
        # popups) are ≤360pt wide or under 400pt tall.
        if not title or wi.w < 500 or wi.h < 400:
            continue
        eligibles.append(wi)
        # only a titled, window-sized window can be the main chat window. The main window
        # is titled with the app's own display name, so this priority check reads the same
        # list rather than keeping a second copy that drifts out of step (#50).
        if best is None or (wi.title in WECHAT_APP_NAMES, wi.w * wi.h, wi.wid) > (
                best.title in WECHAT_APP_NAMES, best.w * best.h, best.wid):
            best = wi

    # The user's window beats every heuristic: a focused frame match is exactly the
    # conversation on screen, and it is fresh each call — no stickiness needed.
    if eligibles:
        focused = _ax_focused_frame(eligibles[0].pid)
        if focused is not None:
            for wi in eligibles:
                if all(abs(a - b) <= 2 for a, b in zip(
                        (wi.x, wi.y, wi.w, wi.h), focused)):
                    return wi

    # stick with the window we already chose: WeChat 4.x keeps several equally-sized
    # windows around, and re-picking each tick let the target jump between them.
    # Only keep that choice within the same priority; a newly available main wins.
    if previous_wid is not None and best is not None and best.wid != previous_wid:
        for w in wins:
            owner = w.get("kCGWindowOwnerName") or ""
            if owner not in WECHAT_APP_NAMES:
                continue
            if int(w.get("kCGWindowNumber") or 0) != previous_wid:
                continue
            title = w.get("kCGWindowName") or ""
            b = dict(w.get("kCGWindowBounds") or {})
            pw = float(b.get("Width", 0))
            ph = float(b.get("Height", 0))
            if (title and pw >= 500 and ph >= 400
                    and (title in WECHAT_APP_NAMES) == (best.title in WECHAT_APP_NAMES)):
                return WindowInfo(wid=previous_wid, pid=int(w.get("kCGWindowOwnerPID") or 0),
                                  title=title, x=float(b.get("X", 0)), y=float(b.get("Y", 0)),
                                  w=pw, h=ph)
    return best


def capture_window(wid: int, out: Path,
                   timeout_s: float = SUBPROCESS_CAPTURE_TIMEOUT_S) -> bool:
    try:
        p = subprocess.run(["screencapture", "-x", "-o", "-l", str(wid), str(out)],
                           capture_output=True, text=True, timeout=timeout_s)
    except subprocess.TimeoutExpired:
        return False
    except OSError:
        # screencapture cannot even start (missing binary, fork or fd failure): report a
        # failed capture so callers degrade the same way as any other miss.
        return False
    return p.returncode == 0 and out.exists() and out.stat().st_size > 1000


def _load_png_image(path: Path, max_size: int | None = None):
    """Load a PNG into pixels that stay alive after the temporary file disappears.

    Reading the file into NSData keeps the image source memory-backed, so deleting the
    temp dir cannot pull the data away. When ``max_size`` (the window's point-size
    square) is known and the capture is larger, resample down to it: ``screencapture``
    writes the window's Retina backing, and Vision's cost tracks pixel count — the
    measured ~100 ms OCR figure is 1x.
    """
    from Foundation import NSData

    data = NSData.dataWithContentsOfFile_(str(path))
    source = Quartz.CGImageSourceCreateWithData(data, None) if data else None
    image = Quartz.CGImageSourceCreateImageAtIndex(source, 0, None) if source else None
    if (image is not None and max_size is not None
            and max(Quartz.CGImageGetWidth(image), Quartz.CGImageGetHeight(image)) > max_size):
        from Quartz import ImageIO

        opts = {ImageIO.kCGImageSourceThumbnailMaxPixelSize: max_size,
                ImageIO.kCGImageSourceCreateThumbnailFromImageAlways: True}
        thumb = Quartz.CGImageSourceCreateThumbnailAtIndex(source, 0, opts)
        if thumb is not None:
            return thumb
    return image


def _window_point_size(wid: int) -> int | None:
    """The window's point-size bounding square, or None if the window is gone.

    Metadata only — no pixel capture, so it cannot hang — mirroring the enumeration
    find_wechat_window() already runs each tick. This is the size a ``nominal``-scale
    capture of that window should match.
    """
    opts = Quartz.kCGWindowListOptionAll | Quartz.kCGWindowListExcludeDesktopElements
    for w in Quartz.CGWindowListCopyWindowInfo(opts, Quartz.kCGNullWindowID):
        if int(w.get("kCGWindowNumber") or 0) != wid:
            continue
        b = dict(w.get("kCGWindowBounds") or {})
        pw, ph = float(b.get("Width", 0)), float(b.get("Height", 0))
        if pw > 0 and ph > 0:
            return int(max(pw, ph))
    return None


# ----------------------------------------------------------------------------- ocr


def _vision_blocks(handler, languages, chat_only: bool, input_top=None,
                   region=None, chat_left=CHAT_PANE_X_MIN,
                   language_correction: bool = True,
                   minimum_text_height: float | None = None) -> list[TextBlock]:
    """Run one Vision text request against a handler that is already built.

    Shared by the file path and the in-memory path so the request settings — the part that
    was measured and tuned — exist exactly once.
    """
    import Vision
    from Quartz import CGRectMake

    blocks: list[TextBlock] = []

    def completion(request, error):
        if error:
            return
        for obs in request.results() or []:
            cands = obs.topCandidates_(1)
            if not cands:
                continue
            c = cands[0]
            bb = obs.boundingBox()
            blocks.append(TextBlock(
                text=c.string().strip(),
                conf=float(c.confidence()),
                x=float(bb.origin.x), y=float(bb.origin.y),
                w=float(bb.size.width), h=float(bb.size.height),
            ))

    req = Vision.VNRecognizeTextRequest.alloc().initWithCompletionHandler_(completion)
    req.setRecognitionLevel_(Vision.VNRequestTextRecognitionLevelAccurate)
    req.setRecognitionLanguages_(list(languages))
    req.setUsesLanguageCorrection_(language_correction)
    if minimum_text_height is not None and hasattr(req, "setMinimumTextHeight_"):
        req.setMinimumTextHeight_(minimum_text_height)
    roi = None
    if chat_only or region is not None:
        # Vision region of interest: normalized, origin BOTTOM-LEFT. Skipping the chat
        # list roughly halves OCR time. Note Vision then reports each observation's
        # bounding box RELATIVE TO THE ROI, so we convert back to full-window space.
        bottom = INPUT_AREA_Y_MIN if input_top is None else 1.0 - input_top
        roi = region if region is not None else (chat_left, bottom, 1.0 - chat_left, 1.0 - bottom)
        req.setRegionOfInterest_(CGRectMake(*roi))
    handler.performRequests_error_([req], None)

    if roi is not None:
        rx, ry, rw, rh = roi
        for b in blocks:
            b.x = rx + b.x * rw
            b.y = ry + b.y * rh
            b.w *= rw
            b.h *= rh
    return blocks


def capture_image(wid: int, nominal: bool = True):
    """Return a window image without calling cancellable-in-no-way CoreGraphics APIs.

    The timed subprocess route is deliberate: a Python thread cannot cancel
    ``CGWindowListCreateImage`` after macOS enters ScreenCaptureKit, while this subprocess
    can be terminated by ``capture_window`` when the system capture service stalls.
    ``screencapture`` writes the window at its Retina backing scale; when ``nominal`` is
    set the result is resampled down to the window's point size, keeping Vision OCR at
    the measured 1x cost and pixel/point consumers at the size they were tuned on.
    """
    try:
        with tempfile.TemporaryDirectory() as td:
            png = Path(td) / "wechat.png"
            if not capture_window(wid, png):
                return None
            return _load_png_image(png, _window_point_size(wid) if nominal else None)
    except Exception:
        return None


def ocr_image(image, languages=("zh-Hans",), chat_only: bool = True, input_top=None,
              region=None, chat_left=CHAT_PANE_X_MIN,
              language_correction: bool = True,
              minimum_text_height: float | None = None) -> list[TextBlock]:
    """Same tuned Vision request, fed a CGImage directly — no PNG encode, no temp file."""
    import Vision
    handler = Vision.VNImageRequestHandler.alloc().initWithCGImage_options_(image, None)
    return _vision_blocks(
        handler, languages, chat_only, input_top, region, chat_left=chat_left,
        language_correction=language_correction,
        minimum_text_height=minimum_text_height)


def warm_ocr() -> float:
    """Pay Vision's one-off recognition-model load on a blank canvas, not a real read.

    The first text recognition in a process costs ~2x steady state (~0.7 s vs ~250 ms)
    while Vision loads its recognition model. Running that first request on a small white
    image needs no WeChat window at all — it works even when WeChat starts after this
    app — so the read loop's first real read finds the framework already paid for.
    Returns the elapsed milliseconds, or -1.0 when the request itself failed.
    """
    cs = Quartz.CGColorSpaceCreateDeviceRGB()
    ctx = Quartz.CGBitmapContextCreate(
        None, 64, 64, 8, 64 * 4, cs, Quartz.kCGImageAlphaPremultipliedLast)
    Quartz.CGContextSetRGBFillColor(ctx, 1.0, 1.0, 1.0, 1.0)
    Quartz.CGContextFillRect(ctx, Quartz.CGRectMake(0, 0, 64, 64))
    image = Quartz.CGBitmapContextCreateImage(ctx)
    t0 = time.perf_counter()
    try:
        ocr_image(image, chat_only=False)
    except Exception:
        return -1.0
    return (time.perf_counter() - t0) * 1000


# ----------------------------------------------------------------- fingerprint

# Fixed grid, independent of window size: a resize re-fingerprints as "different" instead
# of aliasing onto a match. At 128x224 a single chat character still covers a handful of
# cells, so the smallest change anyone could send shifts far more bytes than noise.
_FP_W, _FP_H = 128, 224


def _fingerprint(image, input_top=None, chat_left=CHAT_PANE_X_MIN) -> bytes | None:
    """The chat pane (title band down to just above the input box) as a small grayscale
    thumbnail; None when anything in the pipeline refuses.

    read_conversation() compares this between ticks: the same picture means the pixels
    did not move, so OCR cannot have anything new to report and its ~300 ms can be
    skipped. The input box is excluded on purpose — the caret blinks there, and it would
    keep a quiet screen looking busy forever. The chat list is excluded for the same
    reason (unread badges), which is also why the crop starts at CHAT_PANE_X_MIN.
    """
    import ctypes

    try:
        w = Quartz.CGImageGetWidth(image)
        h = Quartz.CGImageGetHeight(image)
        # Layout constants here are bottom-origin (Vision's convention); CGImage cropping
        # is top-origin, so the band "input-area top edge .. window top" becomes
        # y=0 .. (1 - INPUT_AREA_Y_MIN) from the top.
        crop = Quartz.CGImageCreateWithImageInRect(
            image,
            Quartz.CGRectMake(int(chat_left * w), 0,
                              int((1.0 - chat_left) * w),
                              int((1.0 - INPUT_AREA_Y_MIN if input_top is None else input_top) * h)))
        cs = Quartz.CGColorSpaceCreateDeviceGray()
        buf = ctypes.create_string_buffer(_FP_W * _FP_H)
        ctx = Quartz.CGBitmapContextCreate(
            buf, _FP_W, _FP_H, 8, _FP_W, cs, Quartz.kCGImageAlphaNone)
        Quartz.CGContextDrawImage(ctx, Quartz.CGRectMake(0, 0, _FP_W, _FP_H), crop)
        return buf.raw
    except Exception:
        return None


def _same_frame(a: bytes | None, b: bytes | None) -> bool:
    """True when two fingerprints are the same picture.

    Exact equality covers the static case at C speed. When it fails, a tolerant count
    decides: a few small byte deltas is rendering noise (treat as same, skip OCR),
    anything a person sent rewrites whole glyph cells (treat as changed). Missing a real
    change would mean missing a message, so the threshold sits well under what one
    character produces.
    """
    if a is None or b is None:
        return False
    if a == b:
        return True
    return sum(1 for x, y in zip(a, b) if abs(x - y) >= 8) < 6


def _incoming_bubble_boxes(image, chat_left: float, input_top: float) -> list[tuple]:
    """Find light/dark neutral incoming bubbles that contain no OCR text.

    Vision intentionally suppresses punctuation-only rows such as ``...``.  We do not
    attempt to invent their text; this tiny colour/shape pass only proves that a rounded
    incoming bubble exists below the last readable message, allowing the HUD to stop
    instead of replying to an older sentence.  Coordinates are normalized, top-origin.

    The dominant chat background is measured from every frame, so light/dark themes and
    a resized sidebar are both handled without fixed RGB values.  Only broad, near-neutral
    filled runs qualify; avatars, glyph strokes and green outgoing bubbles do not.
    """
    import ctypes

    try:
        source_w = Quartz.CGImageGetWidth(image)
        source_h = Quartz.CGImageGetHeight(image)
        w = 320
        h = max(120, round(source_h * w / source_w))
        buf = ctypes.create_string_buffer(w * h * 4)
        ctx = Quartz.CGBitmapContextCreate(
            buf, w, h, 8, w * 4, Quartz.CGColorSpaceCreateDeviceRGB(),
            Quartz.kCGImageAlphaPremultipliedLast)
        if ctx is None:
            return []
        Quartz.CGContextDrawImage(ctx, Quartz.CGRectMake(0, 0, w, h), image)
        data = buf.raw
    except Exception:
        return []

    left = max(1, min(w - 2, round(chat_left * w)))
    top = max(1, round((1.0 - TITLE_BAR_Y_MAX) * h))
    bottom = min(h - 2, round(input_top * h))
    if bottom - top < 20:
        return []

    def rgb(x, y):
        i = (y * w + x) * 4
        return data[i], data[i + 1], data[i + 2]

    samples = [rgb(x, y) for y in range(top, bottom, 12)
               for x in range(left + 4, w - 4, 12)]
    if not samples:
        return []
    # The conversation background owns most pixels; channel medians are stable even
    # when several large bubbles are on screen.
    bg = tuple(sorted(c[i] for c in samples)[len(samples) // 2] for i in range(3))
    bg_luma = sum(bg) / 3

    def bubble_pixel(x, y):
        c = rgb(x, y)
        spread = max(c) - min(c)
        luma = sum(c) / 3
        delta = abs(luma - bg_luma)
        return spread <= 10 and 6 <= delta <= 75

    # One run per row is enough for incoming bubbles: they live in the left half of the
    # chat pane. Allow tiny holes so black punctuation inside the fill does not split it.
    pane_w = w - left
    row_runs = []
    scan_right = round(left + pane_w * .72)
    for y in range(top, bottom):
        start = None
        last = None
        gap = 0
        for x in range(left, scan_right):
            if bubble_pixel(x, y):
                if start is None:
                    start = x
                last = x
                gap = 0
            elif start is not None:
                gap += 1
                if gap > 3:
                    if last - start >= max(10, round(w * .035)):
                        row_runs.append((y, start, last))
                    start = last = None
                    gap = 0
        if start is not None and last - start >= max(10, round(w * .035)):
            row_runs.append((y, start, last))

    components = []
    for y, x0, x1 in row_runs:
        match = None
        for comp in reversed(components[-12:]):
            if y - comp[4] > 2:
                continue
            overlap = min(x1, comp[2]) - max(x0, comp[1])
            if overlap >= min(x1 - x0, comp[2] - comp[1]) * .45:
                match = comp
                break
        if match is None:
            components.append([y, x0, x1, y, y])  # top, left, right, first, last
        else:
            match[0] = min(match[0], y)
            match[1] = min(match[1], x0)
            match[2] = max(match[2], x1)
            match[4] = y

    boxes = []
    for y0, x0, x1, _first, y1 in components:
        bw, bh = x1 - x0 + 1, y1 - y0 + 1
        if bw < w * .04 or bh < h * .012 or bh > h * .18:
            continue
        rel_left = (x0 - left) / pane_w
        rel_right = (x1 - left) / pane_w
        if rel_left > .35 or rel_right > .72:
            continue
        boxes.append((x0 / w, y0 / h, bw / w, bh / h))
    return boxes


def _append_unreadable_incoming(image, messages: list[Message], chat_left: float,
                                input_top: float) -> None:
    """Reconcile incoming bubbles, then append a placeholder for one Vision omitted.

    Text geometry is only a first pass.  A quoted row inside a wide incoming bubble can
    sit far enough right to look outgoing, and an unusually tight group nickname can be
    folded into the body.  The neutral bubble pixels settle both cases here, where the
    screenshot is still available.
    """
    boxes = _incoming_bubble_boxes(image, chat_left, input_top)

    def message_matches(box, message):
        x, y, w, h = box
        return (x - .02 <= message.x <= x + w + .02
                and y - .012 <= message.y + message.h / 2 <= y + h + .012)

    def sender_above(box, message):
        """Strong visual evidence that a text row is a group nickname for ``box``."""
        x, y, w, _h = box
        gap = y - (message.y + message.h)
        text = message.text.strip()
        return (message.side in ("them", "unknown")
                and message.sender is None and not message.visual_only
                and message.side != "public" and "\n" not in text
                and 0 < len(text) <= 32
                and -0.008 <= gap <= 0.035
                and x - .04 <= message.x <= x + min(w, .16)
                and message.x + message.w <= x + w + .04
                and not message_matches(box, message))

    # Font size is only a hint in group chats: display-name badges, unusual glyphs and
    # window scaling often make a nickname as tall as the body, which is why James/Lee
    # in real screenshots escaped the pre-OCR-row heuristic. The actual incoming bubble
    # is stronger evidence. A row immediately above and outside that bubble is the
    # sender; bind it to the first message inside the bubble and remove the fake message.
    sender_for_box: dict[tuple, Message] = {}
    claimed_sender_ids = set()
    for box in boxes:
        bodies = [m for m in messages if m.side != "public" and message_matches(box, m)]
        candidates = [m for m in messages if sender_above(box, m)]
        if not candidates:
            continue
        sender_row = min(candidates, key=lambda m: abs(box[1] - (m.y + m.h)))
        sender_for_box[box] = sender_row
        claimed_sender_ids.add(id(sender_row))
        if bodies:
            body = min(bodies, key=lambda m: m.y)
            if body.sender is None:
                body.sender = sender_row.text.strip().rstrip("：:")

    if claimed_sender_ids:
        messages[:] = [m for m in messages if id(m) not in claimed_sender_ids]

    # A tiny isolated OCR row can be either a group-chat sender label or a real short
    # bubble such as "买了". Text geometry alone cannot distinguish them. Production
    # extraction therefore defers the decision until these pixel-derived bubble boxes
    # are available: text inside a neutral incoming bubble stays; text floating above an
    # image/voice item is the sender name and is removed.
    suspected = [m for m in messages if m.suspected_sender]
    confirmed_ids = {
        id(m) for m in suspected if any(message_matches(box, m) for box in boxes)
    }
    if suspected:
        messages[:] = [m for m in messages
                       if not m.suspected_sender or id(m) in confirmed_ids]
    if not boxes:
        return

    # Anything physically inside a neutral incoming bubble belongs to the other side,
    # even when a quoted preview is right-shifted enough for geometry to call it mine.
    # Public rows have no bubble and remain semantic system information even if a noisy
    # colour component happens to overlap them.
    for m in messages:
        matching = [box for box in boxes if message_matches(box, m)]
        if not matching or m.side == "public":
            continue
        m.side = "them"
        box = min(matching, key=lambda b: b[2] * b[3])
        _bx, bubble_y, _bw, _bh = box
        # If extraction folded a tight nickname into the first body line, the first
        # line starts above the bubble while a later line lands inside it. Restore that
        # line as attribution. Ordinary wrapped body text starts below the bubble top,
        # so it cannot enter this branch.
        embedded_lines = [part.strip() for part in m.text.splitlines() if part.strip()]
        candidate_lines = m.lines if len(m.lines) > 1 else embedded_lines
        body_reaches_bubble = (m.last_y >= bubble_y - .012
                               or m.y + m.h > bubble_y + .001)
        if (m.sender is None and len(candidate_lines) > 1
                and m.y < bubble_y - .006 and body_reaches_bubble
                and len(candidate_lines[0].strip()) <= 32):
            sender = candidate_lines[0].strip().rstrip("：:")
            if sender:
                old_bottom = m.y + m.h
                m.sender = sender
                m.lines = candidate_lines[1:]
                m.text = "\n".join(m.lines)
                m.y = bubble_y
                m.h = max(.001, old_bottom - m.y)

    def matched(box):
        return any(message_matches(box, m) for m in messages)

    latest_bottom = max((m.y + m.h for m in messages), default=.10)
    candidates = [b for b in boxes if not matched(b) and b[1] > latest_bottom + .008]
    if not candidates:
        return
    x, y, w, h = max(candidates, key=lambda b: b[1])
    punctuation = _punctuation_only_text(image, (x, y, w, h))
    recovered = None if punctuation else _short_bubble_text(image, (x, y, w, h))
    text = punctuation or (recovered[0] if recovered else "[未识别文字/表情]")
    confidence = 0.70 if punctuation else recovered[1] if recovered else 0.0
    sender_row = sender_for_box.get((x, y, w, h))
    messages.append(Message(
        text=text, side="them", y=y, conf=confidence,
        h=h, lines=[text], x=x, w=w, last_y=y,
        sender=(sender_row.text.strip().rstrip("：:") if sender_row else None),
        visual_only=not bool(punctuation or recovered)))


def _punctuation_only_text(image, box: tuple) -> str | None:
    """Recognize 2–6 tiny repeated full stops inside a Vision-omitted bubble.

    Vision commonly returns no observation at all for ``。。。``.  The bubble pass
    already gives us a very small, safe crop.  Inside that crop, a run of full stops is a
    distinctive set of equally small dark components on one horizontal baseline.  This
    deliberately recognizes only that narrow shape; emoji, stickers and arbitrary marks
    remain the honest ``[未识别文字/表情]`` placeholder.
    """
    import ctypes

    try:
        source_w = Quartz.CGImageGetWidth(image)
        source_h = Quartz.CGImageGetHeight(image)
        bx, by, bw, bh = box
        x0 = max(0, round(bx * source_w))
        y0 = max(0, round(by * source_h))
        w = min(source_w - x0, max(1, round(bw * source_w)))
        h = min(source_h - y0, max(1, round(bh * source_h)))
        crop = Quartz.CGImageCreateWithImageInRect(
            image, Quartz.CGRectMake(x0, y0, w, h))
        buf = ctypes.create_string_buffer(w * h * 4)
        ctx = Quartz.CGBitmapContextCreate(
            buf, w, h, 8, w * 4, Quartz.CGColorSpaceCreateDeviceRGB(),
            Quartz.kCGImageAlphaPremultipliedLast)
        if crop is None or ctx is None:
            return None
        Quartz.CGContextDrawImage(ctx, Quartz.CGRectMake(0, 0, w, h), crop)
        data = buf.raw
    except Exception:
        return None

    # Ignore rounded edges and anti-aliasing at the bubble boundary.
    mx = max(2, round(w * .07))
    my = max(2, round(h * .10))

    def rgb(x, y):
        i = (y * w + x) * 4
        return data[i], data[i + 1], data[i + 2]

    samples = [rgb(x, y) for y in range(my, max(my + 1, h - my), 2)
               for x in range(mx, max(mx + 1, w - mx), 2)]
    if not samples:
        return None
    bubble_luma = sorted(sum(c) / 3 for c in samples)[len(samples) // 2]
    dark_limit = min(170, bubble_luma - 45)
    ink = set()
    for y in range(my, h - my):
        for x in range(mx, w - mx):
            c = rgb(x, y)
            if sum(c) / 3 <= dark_limit and max(c) - min(c) <= 55:
                ink.add((x, y))
    if not ink:
        return None

    total_ink = len(ink)
    components = []
    while ink:
        stack = [ink.pop()]
        points = []
        while stack:
            px, py = stack.pop()
            points.append((px, py))
            for nx in (px - 1, px, px + 1):
                for ny in (py - 1, py, py + 1):
                    if (nx, ny) in ink:
                        ink.remove((nx, ny))
                        stack.append((nx, ny))
        x_min = min(p[0] for p in points)
        x_max = max(p[0] for p in points)
        y_min = min(p[1] for p in points)
        y_max = max(p[1] for p in points)
        cw, ch = x_max - x_min + 1, y_max - y_min + 1
        if 2 <= len(points) <= 40 and cw <= 8 and ch <= 8:
            components.append((len(points), x_min, y_min, x_max, y_max))

    if not 2 <= len(components) <= 6:
        return None
    # Random emoji fragments may contain several dots, but not several same-sized dots
    # on one baseline with almost all dark ink accounted for.
    if sum(c[0] for c in components) < total_ink * .72:
        return None
    centers = sorted(((c[1] + c[3]) / 2, (c[2] + c[4]) / 2,
                      c[3] - c[1] + 1, c[4] - c[2] + 1)
                     for c in components)
    if max(c[1] for c in centers) - min(c[1] for c in centers) > max(3, h * .12):
        return None
    if max(c[2] for c in centers) - min(c[2] for c in centers) > 3:
        return None
    if max(c[3] for c in centers) - min(c[3] for c in centers) > 3:
        return None
    gaps = [centers[i + 1][0] - centers[i][0] for i in range(len(centers) - 1)]
    if any(g < 3 or g > max(20, h * .8) for g in gaps):
        return None
    return "。" * len(components)


def _short_bubble_text(image, box: tuple) -> tuple[str, float] | None:
    """Retry OCR on one visually confirmed bubble at a much larger effective size.

    The full chat pane intentionally runs at nominal 1x for speed. That is enough for
    ordinary lines, but Vision occasionally omits a one-character reply such as ``可``
    altogether. Cropping the already detected bubble makes the same glyph occupy most
    of Vision's input; scaling the crop avoids the framework's small-image floor. This
    path only runs for an otherwise unmatched bubble, so normal reads pay nothing.
    """
    try:
        source_w = Quartz.CGImageGetWidth(image)
        source_h = Quartz.CGImageGetHeight(image)
        bx, by, bw, bh = box
        raw_w = max(1, round(bw * source_w))
        raw_h = max(1, round(bh * source_h))
        # The colour pass sees uninterrupted bubble fill, not its exact outer bounds:
        # glyphs and the debug overlay can split/shorten the component. Expand relative
        # to that component so the full single glyph survives the crop.
        pad_x = max(2, round(raw_w * .18))
        pad_top = max(2, round(raw_h * .18))
        pad_bottom = max(4, round(raw_h * .65))
        x0 = max(0, round(bx * source_w) - pad_x)
        y0 = max(0, round(by * source_h) - pad_top)
        width = min(source_w - x0, raw_w + 2 * pad_x)
        height = min(source_h - y0, raw_h + pad_top + pad_bottom)
        crop = Quartz.CGImageCreateWithImageInRect(
            image, Quartz.CGRectMake(x0, y0, width, height))
        if crop is None:
            return None

        scale = min(8.0, max(3.0, 128.0 / height))
        target_w = max(64, round(width * scale))
        target_h = max(64, round(height * scale))
        ctx = Quartz.CGBitmapContextCreate(
            None, target_w, target_h, 8, target_w * 4,
            Quartz.CGColorSpaceCreateDeviceRGB(),
            Quartz.kCGImageAlphaPremultipliedLast)
        if ctx is None:
            return None
        Quartz.CGContextSetRGBFillColor(ctx, 1, 1, 1, 1)
        Quartz.CGContextFillRect(ctx, Quartz.CGRectMake(0, 0, target_w, target_h))
        Quartz.CGContextSetInterpolationQuality(ctx, Quartz.kCGInterpolationHigh)
        Quartz.CGContextDrawImage(
            ctx, Quartz.CGRectMake(0, 0, target_w, target_h), crop)
        enlarged = Quartz.CGBitmapContextCreateImage(ctx)
        import Vision
        handler = Vision.VNImageRequestHandler.alloc().initWithCGImage_options_(
            enlarged, None)
        # Language correction is valuable for sentences but can suppress a valid
        # isolated character because it has no surrounding language context.
        blocks = _vision_blocks(
            handler, ("zh-Hans",), chat_only=False,
            language_correction=False, minimum_text_height=.005)
    except Exception:
        return None

    bubble_left = (round(bx * source_w) - x0) / width
    bubble_top = (round(by * source_h) - y0) / height
    bubble_right = (round(bx * source_w) + raw_w - x0) / width
    bubble_bottom = (round(by * source_h) + raw_h - y0) / height

    def inside_original_bubble(block):
        center_x = block.x + block.w / 2
        center_top = 1.0 - block.y - block.h / 2
        return (bubble_left - .06 <= center_x <= bubble_right + .06
                and bubble_top - .04 <= center_top <= bubble_bottom + .08)

    # This crop is already proven to be a bubble, so global UI words such as “发送”
    # and “搜索” are valid chat content here. Keep a stricter confidence threshold
    # instead of reusing _is_noise(), which would delete those legitimate short replies.
    readable = [b for b in blocks
                if b.conf >= SHORT_RETRY_MIN_CONF and b.text.strip()
                and inside_original_bubble(b)]
    if not readable:
        return None
    readable.sort(key=lambda b: (-b.y, b.x))
    text = "\n".join(b.text.strip() for b in readable if b.text.strip()).strip()
    if not text or len(text) > 120:
        return None
    return text, min(b.conf for b in readable)


# ---------------------------------------------------------------------- extraction


def _is_noise(b: TextBlock) -> bool:
    if b.conf < MIN_CONF or len(b.text) < MIN_TEXT_LEN:
        return True
    if TIMESTAMP_RE.match(b.text):
        return True
    return any(re.search(pat, b.text) for pat in UI_NOISE)


def extract_chat_title(blocks: list[TextBlock], chat_left=CHAT_PANE_X_MIN) -> str:
    """Read the conversation name from the chat pane's header band.

    Two rows live up there: the title itself and (when a chat is collapsed) a
    "folded chats" banner. We take the topmost readable band and drop the banner.
    """
    cands = [b for b in blocks
             if b.x >= chat_left and b.y > TITLE_BAR_Y_MAX
             and not _is_noise(b)]
    # No length cap on purpose: an empty title collides reply keys across chats
    # (key = (chat_title, text)), which is worse than the occasional single-glyph
    # OCR smudge promoted to a title.
    # WeChat titles are left-aligned; centered headers would need layout detection.
    # A real contact name can be one character, so length cannot tell title from controls.
    starts = [b for b in cands if b.x < (chat_left + 1) / 2]
    if not starts:
        return ""
    top_y = max(b.y for b in starts)
    band = sorted((b for b in cands if abs(top_y - b.y) < 0.03), key=lambda b: b.x)
    keep = [band[0]]
    for b in band[1:]:
        # Join adjacent OCR fragments, including a short suffix; stop before controls.
        if b.x - keep[-1].x_right > 1.5 * max(b.h, keep[-1].h):
            break
        keep.append(b)
    title = " ".join(b.text for b in keep).strip()
    # WeChat appends a changing member count; it is not part of the conversation key.
    return re.sub(r"\s*[（(]\s*\d+\s*[）)]\s*$", "", title).strip()


def message_side(x: float, width: float, chat_left=CHAT_PANE_X_MIN) -> str:
    """Conservative text geometry: a center alone cannot identify a wide bubble.

    Only accept text anchored clearly to one side of the calibrated chat pane.
    Wide text spanning both anchors and isolated central fragments are ambiguous;
    keep them for context/overlay, but never treat them as an incoming reply target.
    """
    right = x + width
    pane = max(.01, 1.0 - chat_left)
    rel_x = (x - chat_left) / pane
    rel_right = (right - chat_left) / pane
    if rel_x >= .50 or (rel_x >= .18 and rel_right >= .72):
        return "me"
    if rel_x <= .30 and rel_right < .72:
        return "them"
    return "unknown"


def _is_public_info(text: str) -> bool:
    """Whether text is a WeChat-generated row shared with the whole conversation."""
    compact = re.sub(r"\s+", "", text).strip("。. ")
    return bool(compact and PUBLIC_INFO_RE.fullmatch(compact))


def _resolve_short_unknown_sides(messages: list[Message]) -> None:
    """Resolve only short unknown rows that align with both known chat anchors.

    Vision places a punctuation-only or punctuation-prefixed text box a few pixels to
    the right of an ordinary Chinese glyph. Near the conservative x=.50 boundary that
    can turn a clearly left-aligned incoming bubble into ``unknown``; the HUD then falls
    back to an older incoming message. Use the repeated left edge of known incoming text
    and repeated right edge of known outgoing text as evidence, but only when both sides
    are visible and the short row is decisively closer to one. Wide/central rows remain
    unknown, preserving the no-reply-on-ambiguous-message safety rule.
    """
    them_lefts = [m.x for m in messages if m.side == "them"]
    me_rights = [m.x + m.w for m in messages if m.side == "me"]
    if not them_lefts or not me_rights:
        return
    them_anchor = sorted(them_lefts)[len(them_lefts) // 2]
    me_anchor = sorted(me_rights)[len(me_rights) // 2]
    for m in messages:
        if m.side != "unknown" or m.w > .30:
            continue
        them_delta = abs(m.x - them_anchor)
        me_delta = abs(m.x + m.w - me_anchor)
        if them_delta <= .04 and them_delta + .04 < me_delta:
            m.side = "them"
        elif me_delta <= .04 and me_delta + .04 < them_delta:
            m.side = "me"


def extract_messages(blocks: list[TextBlock], max_messages: int = 12, input_top=None,
                     chat_left=CHAT_PANE_X_MIN,
                     defer_small_sender_filter: bool = False) -> list[Message]:
    """Turn raw OCR blocks into an ordered list of chat messages (bottom = newest)."""
    chat = [b for b in blocks
            if b.x >= chat_left
            and (INPUT_AREA_Y_MIN if input_top is None else 1.0 - input_top) < b.y < TITLE_BAR_Y_MAX
            and not _is_noise(b)]
    if not chat:
        return []

    # Vision y is bottom-origin and bb.origin.y is the box's BOTTOM edge. Convert to a
    # top-origin TOP edge (1 - y - h) so the stored y is literal: "distance from the
    # pane's top to where this box starts". The old 1 - y stored the bottom edge's
    # distance from the top — orderings and gap thresholds did not care (the transform
    # is monotonic), but the YOLO overlay draws y as the top edge and every box sank by
    # one box-height. Sorting and the fold/group logic below are unchanged either way.
    for b in chat:
        b.y = 1.0 - b.y - b.h
    chat.sort(key=lambda b: b.y)

    # group blocks that sit on the same visual line
    lines: list[list[TextBlock]] = []
    for b in chat:
        if lines and abs(b.y - lines[-1][0].y) < 0.012:
            lines[-1].append(b)
        else:
            lines.append([b])

    merged = []
    for group in lines:
        group.sort(key=lambda b: b.x)
        text = " ".join(b.text for b in group)
        merged.append(TextBlock(text=text, conf=min(b.conf for b in group),
                                x=min(b.x for b in group), y=group[0].y,
                                w=max(b.x_right for b in group) - min(b.x for b in group),
                                h=max(b.h for b in group)))

    def classify(block: TextBlock) -> str:
        return "public" if _is_public_info(block.text) else message_side(
            block.x, block.w, chat_left)

    per_line = sorted(merged, key=lambda b: b.y)
    # A long centered system notice may be returned as two or three OCR rows. Join it
    # before direction and sender-name inference; otherwise each fragment looks like a
    # normal left/right message even though their complete text is a public row.
    public_joined: list[TextBlock] = []
    i = 0
    while i < len(per_line):
        if _is_public_info(per_line[i].text):
            public_joined.append(per_line[i])
            i += 1
            continue
        joined = None
        for size in range(min(3, len(per_line) - i), 1, -1):
            chunk = per_line[i:i + size]
            # Do not swallow a complete public row into the ordinary message before it.
            if any(_is_public_info(part.text) for part in chunk[1:]):
                continue
            if any(not 0 <= chunk[j + 1].y - chunk[j].y < .06
                   for j in range(len(chunk) - 1)):
                continue
            text = "\n".join(part.text for part in chunk)
            if not _is_public_info(text):
                continue
            left = min(part.x for part in chunk)
            right = max(part.x_right for part in chunk)
            top = chunk[0].y
            bottom = max(part.y + part.h for part in chunk)
            joined = TextBlock(text=text, conf=min(part.conf for part in chunk),
                               x=left, y=top, w=right - left, h=bottom - top)
            i += size
            break
        if joined is None:
            joined = per_line[i]
            i += 1
        public_joined.append(joined)
    per_line = public_joined

    # fold continuation lines (same side, tight vertical gap, no new sender header)
    # Classify sender headers BEFORE folding; otherwise a tight nickname/body pair
    # becomes one multiline message and the old post-fold name detector misses it.
    # Compare adjacent font heights rather than a fraction of the window height.
    headers = set()
    for i, b in enumerate(per_line[:-1]):
        nxt = per_line[i + 1]
        if (i > 0 and QUOTE_LINE_RE.match(b.text) and b.h <= .026
                and per_line[i - 1].h >= .03
                and 0 <= b.y - per_line[i - 1].y <= .045
                and abs(b.x - per_line[i - 1].x) < .02):
            continue  # an inset quoted preview, not the next bubble's sender
        if (classify(b) == classify(nxt) == "them"
                and len(b.text) <= 32 and b.h <= nxt.h * .78
                and abs(b.x - nxt.x) < .03
                and b.h <= nxt.y - b.y <= max(.16, b.h * 4)):
            headers.add(i)
    messages: list[Message] = []
    pending_sender = None
    for i, b in enumerate(per_line):
        if i in headers:
            pending_sender = b.text.strip().rstrip("：:")
            continue
        side = classify(b)
        # fold against the LAST folded line, not the message's first: comparing against
        # the first line made every line from the third on measure ≥2 line-pitches away,
        # so any 3+ line message was split into ≤2-line chunks — the judge then only ever
        # saw the tail chunk, and the overlay drew a box per chunk
        gap = (b.y - messages[-1].last_y) if messages else 1.0
        # OCR gives us text boxes, not bubble boxes.  In a right-aligned outgoing bubble,
        # wrapped text is left-aligned inside the bubble: its long first row reaches the
        # right anchor and classifies as ``me``, while a short second row can look like
        # ``them`` when judged in isolation.  A tight, left-aligned next row is therefore
        # continuation evidence independent of its provisional side.  Once folded, the
        # union bounds reach the correct anchor and we classify the whole bubble below.
        x_shift = abs(b.x - messages[-1].x) if messages else 1.0
        aligned = messages and x_shift < 0.02
        compatible = messages and side != "public" and messages[-1].side != "public" \
            and (side == messages[-1].side
                                   or "unknown" in (side, messages[-1].side))
        # When both provisional sides are known but opposite, demand much stronger
        # same-bubble evidence.  This catches a short wrapped outgoing row whose left
        # edge is effectively identical to the long row above, without joining two
        # genuinely opposite bubbles that merely happen to start near each other.
        wrapped_opposite = (messages and side != messages[-1].side
                            and side not in ("unknown", "public")
                            and messages[-1].side not in ("unknown", "public")
                            and x_shift < 0.008 and 0 <= gap < 0.038)
        if (pending_sender is None and aligned and 0 <= gap < 0.045
                and (compatible or wrapped_opposite)):
            m = messages[-1]
            quoted = QUOTE_LINE_RE.match(b.text)
            # Quoted previews use smaller, muted type inside the same bubble. A plain
            # "name: words" line at normal body size stays ordinary message text.
            quote_line = (m.side in ("them", "me") and b.h <= .026
                          and m.h >= .03 and quoted is not None
                          and "://" not in b.text)
            if quote_line:
                m.quote_sender = quoted.group(1).strip()
                m.quote_text = quoted.group(2).strip()
            elif m.quote_text and b.h <= .026:
                m.quote_text += "\n" + b.text
            else:
                m.lines.append(b.text)
                m.text = "\n".join(m.lines)
            m.conf = min(m.conf, b.conf)
            # grow the bounding box to cover the folded line (m.y stays the top line's)
            bottom = max(m.y + m.h, b.y + b.h)
            right = max(m.x + m.w, b.x_right)
            m.x = min(m.x, b.x)
            m.w = right - m.x
            if not quote_line and not (m.quote_text and b.h <= .026):
                m.side = "public" if _is_public_info(m.text) else message_side(
                    m.x, m.w, chat_left)
            m.h = bottom - m.y
            m.last_y = b.y
        else:
            messages.append(Message(text=b.text, side=side, y=b.y, conf=b.conf,
                                    h=b.h, lines=[b.text], x=b.x, w=b.w,
                                    last_y=b.y, sender=pending_sender))
            pending_sender = None

    _resolve_short_unknown_sides(messages)
    # Stray sender names: WeChat renders one above every bubble — including
    # image-only messages, whose media OCR cannot read — so a short them line that
    # ended up as a message of its own is a name, never something to judge. Our own
    # bubbles have no name above them, and short outgoing text can be just as small
    # in a tall window, so only the them side is dropped. (#62)
    small_incoming = [
        m for m in messages
        if (m.side == "them" and "\n" not in m.text
            and len(m.text) <= 16 and m.h < USERNAME_H_MAX)
    ]
    # Two aligned small incoming rows are much more likely to be successive short
    # bubbles ("不够啊" / "还要交社保") than two orphaned sender labels.
    # Preserve that sequence while still dropping an isolated name above image/voice
    # content, including when an outgoing message happens to follow it.
    short_bubble_ids = {
        id(m) for m in small_incoming
        if any(other is not m
               and abs(other.y - m.y) <= .12
               and abs(other.x - m.x) <= .04
               for other in small_incoming)
    }
    small_incoming_ids = {id(m) for m in small_incoming}
    for m in small_incoming:
        if id(m) not in short_bubble_ids:
            m.suspected_sender = True
    if defer_small_sender_filter:
        return messages[-max_messages:]
    named = [m for m in messages
             if id(m) not in small_incoming_ids or id(m) in short_bubble_ids]
    return named[-max_messages:]


def looks_like_sender_name(msg: Message, following: Message | None) -> bool:
    """Heuristic: group chats render the sender name as a short line above the bubble."""
    if following is None:
        return False
    t = msg.text.strip()
    if len(t) > 16 or "\n" in t:
        return False
    gap = following.y - msg.y
    return gap > 0.045


# ---------------------------------------------------------------------- public API


def read_calibrated(image, calibration, window, max_messages=12, capture_ms=0.0):
    """Explicit selected region. Never infer a fill target from a message selection.

    capture_ms: time read_conversation already spent finding the window and capturing
    before handing us the pixels. Timing is reported from the caller's t0, same
    caliber as the plain path — without it this branch reported capture=0 and the
    real capture cost vanished from the read log (#110).
    """
    from calibrated_messages import extract, recover_numeric_bubbles
    t0 = time.perf_counter()
    x,y,w,h = calibration.rect()
    blocks = ocr_image(image, region=(x,1-y-h,w,h))
    header = ocr_image(image, region=(x,1-y,w,y))
    candidates = [b for b in header if not _is_noise(b) and b.x < x+w*.75]
    title = ""
    if candidates:
        top = max(b.y+b.h for b in candidates)
        line = [b for b in candidates if top-(b.y+b.h) < b.h*.6]
        title = " ".join(b.text for b in sorted(line,key=lambda b:b.x))
    blocks = recover_numeric_bubbles(image, blocks, (x,y,w,h))
    msgs = extract(image, blocks, (x,y,w,h), max_messages)
    elapsed = (time.perf_counter()-t0)*1000
    return {"ok": True, "unchanged": False, "window": window, "messages": msgs,
            "chat_title": title, "n_blocks": len(blocks), "fingerprint": None,
            "layout": (window['wid'],window['w'],window['h'],calibration.serialize()),
            "input_rect": None, "manual_calibration": True,
            "timing_ms": {"capture":capture_ms, "ocr":elapsed,
                          "total":capture_ms+elapsed, "capture_path":"manual"}}


def read_conversation(max_messages: int = 12, previous_wid: int | None = None,
                      prev_fingerprint: bytes | None = None, prev_layout=None, calibration=None) -> dict:
    """One-shot read: find window -> capture -> OCR -> messages.

    Pass the previous call's "fingerprint" and an unchanged chat pane short-circuits
    before OCR: ok=True with "unchanged": True, empty messages, and the window's current
    geometry — the caller reuses what it last read and keeps positioning from fresh
    coordinates. The layout key must also match: resizing the window or input panel
    always forces fresh extraction. Both capture paths use the same image for the
    input boundary, fingerprint and OCR; an unresolved boundary yields no messages.
    """
    t0 = time.perf_counter()
    win = find_wechat_window(previous_wid)
    if win is None:
        return {"ok": False, "error": "WeChat main window not found", "messages": []}

    # Always use the subprocess path in production. A Python thread cannot cancel
    # CGWindowListCreateImage once macOS enters ScreenCaptureKit, while a timed
    # subprocess can be terminated and the HUD worker remains reusable.
    image = None
    capture_path = "subprocess"
    window = {"wid": win.wid, "title": win.title, "w": win.w, "h": win.h,
              "x": win.x, "y": win.y}
    # Use the same captured pixels for the input boundary and OCR. Never reuse a
    # previous window's boundary after resizing or switching windows.
    if image is None:
        with tempfile.TemporaryDirectory() as td:
            png = Path(td) / "wechat.png"
            if capture_window(win.wid, png):
                image = _load_png_image(png)
    if calibration is not None:
        if image is None:
            return {"ok": False, "error": "capture failed", "messages": []}
        if not calibration.matches(win):
            return {"ok": True, "unchanged": False, "messages": [], "window": window,
                    "calibration_error": "窗口尺寸已改变，请重新校准消息区域。"}
        capture_ms = (time.perf_counter() - t0) * 1000
        return read_calibrated(image, calibration, window, max_messages,
                               capture_ms=capture_ms)
    from input_region import input_outline
    visual_outline = None
    try:
        visual_outline = input_outline(image) if image is not None else None
    except Exception:
        visual_outline = None
    outline = visual_outline
    # AX is a fallback for themes with no visible separator. Its text-area top is
    # sufficient to exclude drafts, even if the toolbar above it remains visible.
    if outline is None:
        import fill
        target = fill.locate_input(window)
        rect = target.get("rect")
        if rect:
            x, y, w, h = rect
            outline = ((x-win.x)/win.w, (y-win.y)/win.h, w/win.w, h/win.h)
    input_top = outline[1] if outline else None
    if input_top is not None and not .2 < input_top < .95:
        outline = None
        input_top = None
    # The composer begins exactly at the live sidebar/chat divider in WeChat 4.x.
    # Measuring it every frame keeps OCR aligned while the user drags the sidebar.
    # AX fallback points inside the editor, so only the visual outline may define it.
    # input_outline follows the inner composer stroke, a few pixels to the right of the
    # actual divider. Keep a small proportional gutter so the first title glyph is not
    # clipped while still excluding the sidebar's unread badges.
    chat_left = max(.15, visual_outline[0] - .015) if visual_outline else CHAT_PANE_X_MIN
    if not .15 < chat_left < .60:
        chat_left = CHAT_PANE_X_MIN
    layout = (win.wid, win.w, win.h, input_top, round(chat_left, 4))
    visual_rect = ((win.x + outline[0]*win.w, win.y + outline[1]*win.h,
                    outline[2]*win.w, outline[3]*win.h) if outline else None)
    fingerprint = (_fingerprint(image, input_top, chat_left)
                   if image is not None and outline else None)
    if layout == prev_layout and _same_frame(fingerprint, prev_fingerprint):
        total = (time.perf_counter() - t0) * 1000
        timing = {"capture": total, "ocr": 0.0, "total": total,
                  "capture_path": capture_path}
        return {"ok": True, "unchanged": True, "messages": [], "fingerprint": fingerprint,
                "chat_title": "", "window": window, "n_blocks": 0,
                "layout": layout, "input_rect": visual_rect,
                "chat_left": chat_left, "timing_ms": timing}

    t_cap = time.perf_counter()
    if image is None:
        return {"ok": False, "error": "capture failed", "messages": []}
    blocks = ocr_image(image, input_top=input_top, chat_left=chat_left)
    t_ocr = time.perf_counter()

    chat_title = extract_chat_title(blocks, chat_left=chat_left)
    msgs = (extract_messages(blocks, max_messages=max_messages, input_top=input_top,
                             chat_left=chat_left, defer_small_sender_filter=True)
            if outline else [])
    if outline:
        _append_unreadable_incoming(image, msgs, chat_left, input_top)
        msgs = msgs[-max_messages:]
    timing = {"capture": (t_cap - t0) * 1000, "ocr": (t_ocr - t_cap) * 1000,
              "total": (t_ocr - t0) * 1000, "capture_path": capture_path}
    return {
        "ok": True,
        "unchanged": False,
        "layout": layout,
        "input_rect": visual_rect,
        "chat_left": chat_left,
        "input_unresolved": outline is None,
        "chat_title": chat_title,
        "window": window,
        "messages": msgs,
        "timing_ms": timing,
        "n_blocks": len(blocks),
        "fingerprint": fingerprint,
    }


if __name__ == "__main__":
    import json

    res = read_conversation()
    if not res["ok"]:
        print("ERROR:", res["error"])
        raise SystemExit(1)
    print(f"window {res['window']['w']:.0f}x{res['window']['h']} "
          f"capture={res['timing_ms']['capture']:.0f}ms ocr={res['timing_ms']['ocr']:.0f}ms "
          f"blocks={res['n_blocks']}")
    print("--- messages (top to bottom) ---")
    for m in res["messages"]:
        print(f"  [{m.side:4s}] y={m.y:.3f} conf={m.conf:.2f} | {m.text}")
